api_platform:
    title: Tasks  for Kodana
    version: 1.0.0
    use_symfony_listeners: true
    defaults:
        validation_groups: ['Default']
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
